package topdeep.autotest.entity.data;

import java.util.Date;

public class AtTestResult {

    private String id;

    private String superAdminId;

    private String testProjectId;

    private String testTaskId;

    private Date beginTime;

    private Date endTime;

    private String testState;

    private Integer testNo;

    private String testResult;

    private String startId;

    private String startName;

    private String testTaskName;

    private Integer testResultNo;
    
    
    public AtTestResult(String id, String superAdminId, String testProjectId, String testTaskId, Date beginTime, Date endTime, String testState, Integer testNo, String testResult, String startId, String startName, String testTaskName, Integer testResultNo) {
        this.id = id;
        this.superAdminId = superAdminId;
        this.testProjectId = testProjectId;
        this.testTaskId = testTaskId;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.testState = testState;
        this.testNo = testNo;
        this.testResult = testResult;
        this.startId = startId;
        this.startName = startName;
        this.testTaskName = testTaskName;
        this.testResultNo = testResultNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table at_test_result
     *
     * @mbggenerated
     */
    public AtTestResult() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.ID
     *
     * @return the value of at_test_result.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.ID
     *
     * @param id the value for at_test_result.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.SUPER_ADMIN_ID
     *
     * @return the value of at_test_result.SUPER_ADMIN_ID
     *
     * @mbggenerated
     */
    public String getSuperAdminId() {
        return superAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.SUPER_ADMIN_ID
     *
     * @param superAdminId the value for at_test_result.SUPER_ADMIN_ID
     *
     * @mbggenerated
     */
    public void setSuperAdminId(String superAdminId) {
        this.superAdminId = superAdminId == null ? null : superAdminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.TEST_PROJECT_ID
     *
     * @return the value of at_test_result.TEST_PROJECT_ID
     *
     * @mbggenerated
     */
    public String getTestProjectId() {
        return testProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.TEST_PROJECT_ID
     *
     * @param testProjectId the value for at_test_result.TEST_PROJECT_ID
     *
     * @mbggenerated
     */
    public void setTestProjectId(String testProjectId) {
        this.testProjectId = testProjectId == null ? null : testProjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.TEST_TASK_ID
     *
     * @return the value of at_test_result.TEST_TASK_ID
     *
     * @mbggenerated
     */
    public String getTestTaskId() {
        return testTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.TEST_TASK_ID
     *
     * @param testTaskId the value for at_test_result.TEST_TASK_ID
     *
     * @mbggenerated
     */
    public void setTestTaskId(String testTaskId) {
        this.testTaskId = testTaskId == null ? null : testTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.BEGIN_TIME
     *
     * @return the value of at_test_result.BEGIN_TIME
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.BEGIN_TIME
     *
     * @param beginTime the value for at_test_result.BEGIN_TIME
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.END_TIME
     *
     * @return the value of at_test_result.END_TIME
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.END_TIME
     *
     * @param endTime the value for at_test_result.END_TIME
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.TEST_STATE
     *
     * @return the value of at_test_result.TEST_STATE
     *
     * @mbggenerated
     */
    public String getTestState() {
        return testState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.TEST_STATE
     *
     * @param testState the value for at_test_result.TEST_STATE
     *
     * @mbggenerated
     */
    public void setTestState(String testState) {
        this.testState = testState == null ? null : testState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.TEST_NO
     *
     * @return the value of at_test_result.TEST_NO
     *
     * @mbggenerated
     */
    public Integer getTestNo() {
        return testNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.TEST_NO
     *
     * @param testNo the value for at_test_result.TEST_NO
     *
     * @mbggenerated
     */
    public void setTestNo(Integer testNo) {
        this.testNo = testNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.TEST_RESULT
     *
     * @return the value of at_test_result.TEST_RESULT
     *
     * @mbggenerated
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.TEST_RESULT
     *
     * @param testResult the value for at_test_result.TEST_RESULT
     *
     * @mbggenerated
     */
    public void setTestResult(String testResult) {
        this.testResult = testResult == null ? null : testResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.START_ID
     *
     * @return the value of at_test_result.START_ID
     *
     * @mbggenerated
     */
    public String getStartId() {
        return startId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.START_ID
     *
     * @param startId the value for at_test_result.START_ID
     *
     * @mbggenerated
     */
    public void setStartId(String startId) {
        this.startId = startId == null ? null : startId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.START_NAME
     *
     * @return the value of at_test_result.START_NAME
     *
     * @mbggenerated
     */
    public String getStartName() {
        return startName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.START_NAME
     *
     * @param startName the value for at_test_result.START_NAME
     *
     * @mbggenerated
     */
    public void setStartName(String startName) {
        this.startName = startName == null ? null : startName.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.TEST_TASK_NAME
     *
     * @return the value of at_test_result.TEST_TASK_NAME
     *
     * @mbggenerated
     */
    public String getTestTaskName() {
        return testTaskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.TEST_TASK_NAME
     *
     * @param testTaskName the value for at_test_result.TEST_TASK_NAME
     *
     * @mbggenerated
     */
    public void setTestTaskName(String testTaskName) {
        this.testTaskName = testTaskName == null ? null : testTaskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_test_result.TEST_RESULT_NO
     *
     * @return the value of at_test_result.TEST_RESULT_NO
     *
     * @mbggenerated
     */
    public Integer getTestResultNo() {
        return testResultNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_test_result.TEST_RESULT_NO
     *
     * @param testResultNo the value for at_test_result.TEST_RESULT_NO
     *
     * @mbggenerated
     */
    public void setTestResultNo(Integer testResultNo) {
        this.testResultNo = testResultNo;
    }

}
